### ISSUE TITLE
Host Pretrained Models

### ISSUE THREAD

**Issue by bmccann** [salesforce/decaNLP#1]
Provide a set of models trained for single tasks and on the entire DecaNLP.

**Comment by xuf12** [comment]
When would the pertained models be uploaded online?

**Comment by bmccann** [comment]
Just added the first one. It is the best MQAN trained on decaNLP (pretrained on SQuAD). I'll be adding more of the multitask models and the single tasks models now that I ironed out how we'll be hosting them, etc.

**Comment by impredicative** [comment]
@bmccann If it matters, you can decrease your bandwidth costs for hosting this model by at least 12% by using `tar.xz` instead of `tar.gz`.

**Comment by bmccann** [comment]
Just updated the README with instructions for how to run the pretrained single-task state-of-the-art WikiSQL MQAN. https://github.com/salesforce/WikiSQL/pull/23

**Comment by bmccann** [comment]
I have those and can add them in

**Comment by xxxxxyt** [comment]
Is the optimizer state file of the pre-trained model available now? Could you please tell me where can I get it? Thanks!

**Comment by bmccann** [comment]
They are uploaded, and they should work on https://github.com/salesforce/decaNLP/pull/40. Holding off on merging that right now b/c mem usage seems higher after migration and the default batch size (token level) of 10k seems to run out of memory now. If you reduce that to 9k, seems to be ok.

**Comment by bmccann** [comment]
Just merged, so the CPU versions of the models, the optimizer state files, etc. should all be there now!

**Comment by xxxxxyt** [comment]
> They are uploaded, and they should work on #40. Holding off on merging that right now b/c mem usage seems higher after migration and the default batch size (token level) of 10k seems to run out of memory now. If you reduce that to 9k, seems to be ok.

Is this pre-trained model also trained on squad in the first 75k iterations?

**Comment by bmccann** [comment]
1e9605f246b9e05199b28bde2a2093bc49feeeaa
