### ISSUE TITLE
  Could not resolve host: developer.download.nvidia.com

### ISSUE THREAD

**Issue by loveJasmine** [salesforce/decaNLP#10]
mldl@mldlUB1604:~/ub16_prj/decaNLP/dockerfiles$ sudo docker build -t decanlp .
[sudo] password for mldl: 
Sending build context to Docker daemon  3.584kB
Step 1/22 : FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
 ---> 222eeacc095c
Step 2/22 : RUN apt-get update         && apt-get install -y --no-install-recommends             git             ssh             build-essential             locales             ca-certificates             curl             unzip
 ---> Running in 6c3f7128c405
Err:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:2 http://archive.ubuntu.com/ubuntu xenial InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease
  Could not resolve host: developer.download.nvidia.com
Err:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:5 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  InRelease
  Could not resolve host: developer.download.nvidia.com

**Comment by bmccann** [comment]
Thanks for bringing up this pain point. I’m not entirely sure why you’re having this issue, but I’ll try to build the docker image and push it to a public repository. I think as long as you have the right drivers you then would not need to build the image yourself.

**Comment by bmccann** [comment]
Can you try running these two lines: 

`docker pull bmccann/decanlp` 
`docker tag bmccann/decanlp decanlp` 


and then let me know if you can run the commands from the README.

**Comment by bmccann** [comment]
I haven’t heard back so I’m closing this issue for now. Let me know if this problem persisted.
