### ISSUE TITLE
can we run this project without docher?

### ISSUE THREAD

**Issue by loveJasmine** [salesforce/decaNLP#11]

**Comment by t-vi** [comment]
I seem to be able to start it with my plain torch (not even conda) installation, but it's harder to support people doing so.

**Comment by loveJasmine** [comment]
just give a simple example, thanks

**Comment by bmccann** [comment]
You can run this without docker. You have to go through the setup manually though, pulling the lines you need from the docker file to install appropriate packages. Then you can run the python commands directly without pretending nvidia-docker.

**Comment by Timopheym** [comment]
I succeded running it without docker, but i was forced to place deca folder to the root of FS due / in the start of the paths in some script.
