### ISSUE TITLE
Runtime error： the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)

### ISSUE THREAD

**Issue by mongolia19** [salesforce/decaNLP#14]
Hi，
I am running the code using my own corpus with format of squad， and I did not change any other settings. But when I ran the code， I encountered this issue：

Traceback (most recent call last):
  File "train.py", line 369, in <module>
    main()
  File "train.py", line 365, in main
    run(args, run_args, world_size=args.world_size)
  File "train.py", line 313, in run
    writer=writer if rank==0 else None, save_every=args.save_every, start_iteration=start_iteration)
  File "train.py", line 180, in train
    val_loss, metric_dict = validate(val_task, val_iter, model, logger, field, world_size, rank, num_print=args.num_print, args=args)
  File "/data01/bao/decaNLP/validate.py", line 72, in validate
    loss, prediction   answers, results = gather_results(model, val_iter, field, world_size, optional_names=optional_names)
f sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)
  File "/data01/bao/decaNLP/validate.py", line 48, in gather_results
    loss, predictions, answers, outputs = compute_validation_outputs(model, val_iter, field, optional_names=optional_names)
  File "/data01/bao/decaNLP/validate.py", line 9, in compute_validation_outputs
    l, p = model(batch)
  File "/home/kaifa/anaconda3/envs/tensorflow/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/data01/bao/decaNLP/models/multitask_question_answering_network.py", line 124, in forward
    oov_to_limited_idx, rnn_state=context_rnn_state).data
  File "/data01/bao/decaNLP/models/multitask_question_answering_network.py", line 196, in greedy
    outs[:, t] = Variable(preds.data.cpu().apply_(self.map_to_full), volatile=True)
RuntimeError: expand(_**torch.LongTensor{[256, 1]}, size=[256])**_: the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)

It seems that the torch need a size with two dimensions but you only offer one？ Does size[256] work correctly here？ Or do I need to change this?
Thank you!

**Comment by ayushman-shopin** [comment]
I am getting the same error.

**Comment by directlinks** [comment]
Hi, Mongolia.
were you able to solve this issue? I am getting the same error.

**Comment by mongolia19** [comment]
@directlinks Sorry， I am still working on it， maybe you can try pytorch gpu version to try to avoid this issue？

**Comment by mongolia19** [comment]
I am using pytorch cpu version， does this matter？

**Comment by directlinks** [comment]
@mongolia19  I was using the pytorch cuda version 8, but still got the same error

**Comment by directlinks** [comment]
@mongolia19 It worked! Try with pytorch 0.3 cuda9.0 version instead of pytorch 0.4. Install all the files as mentioned i.e. docker and nvidia-docker.

**Comment by mongolia19** [comment]
@directlinks Great job， I will give it a try！Thank you!

**Comment by bmccann** [comment]
Unfortunately, for us to guarantee the code will work you have to make sure to use all of the versions of libraries specified in the Dockerfile. If you deviate, things might break. Glad this got sorted out when using the currently specified versions. We’ll make a separate branch for PyTorh 0.4.

**Comment by mongolia19** [comment]
@bmccann  Great！Please support pytorch 0.4！I think most people are turning to 0.4 now！Really thank you！
