### ISSUE TITLE
schema.txt

### ISSUE THREAD

**Issue by t-vi** [salesforce/decaNLP#2]
Hi,

congrats on the awesome results!

If you allow me to ask
```
mv local_data/schema.txt .data/schema/
```
should I expect to find schema.txt in local_data?

Best regards

Thomas

**Comment by bmccann** [comment]
Yes absolutely. Looks like it might have gotten removed as we refactored. I’ll add it back in ASAP.

**Comment by bmccann** [comment]
This should be taken care of now. Thanks for brining that to my attention. 554fe5ea9c5770bcae473024403012cef51d6f67

**Comment by t-vi** [comment]
Thanks Bryan!
