### ISSUE TITLE
experiments.sh file is missing? 

### ISSUE THREAD

**Issue by ajaynagesh** [salesforce/decaNLP#22]
Where can I find the experiments.sh file mentioned in the README file ? Thanks!

**Comment by bmccann** [comment]
I'll add this back, but for now:

For single tasks, the command mentioned in the Training section in the README for SQuAD can be altered with the task of choice, and you can keep everything else the same.

For multitask experiments, you can use the example in the Training section of the README to train using the fully joint, round robin strategy. To use the anti-curriculum strategies, you can use --n_jumpstart to set how many tasks you want to train in the pretraining phase (based on the list of tasks provided for --train_tasks), and you can use --jump_start to specify the number of iterations that each of those pretrained tasks should get (recommended to be around 75k).

**Comment by ajaynagesh** [comment]
Very helpful, thank you! I'll keep this issue open just as a placeholder and close it when the file is uploaded. Hope that is okay ..

**Comment by bmccann** [comment]
For the most part this is really just the same commands from the README with minor variations, so I don't think it is necessary.
