### ISSUE TITLE
is there a way to run this project without using CUDA? 

### ISSUE THREAD

**Issue by rohith46** [salesforce/decaNLP#24]
I have installed docker image of decaNLP on my local and want to try custom dataset(Json dict file: context, questions, answers). I don't have Nvidia hardware to install CUDA. so using docker instead of Nvidia-docker (( docker run -it --rm -v `pwd`:/decaNLP/  decanlp bash -c "python /decaNLP/predict.py --evaluate valid --path /decaNLP/mqan_decanlp_qa_first --checkpoint_name model.pth --tasks my_custom_dataset" ))

Is there a possibility to try model.pth (pre-trained model) to predict on the custom dataset without CUDA dependency?

**Comment by bmccann** [comment]
Yes there should be; I'll upload a separate Dockerfile/image for CPU usage, and I might need to reupload the model checkpoints if they were saved on GPU.

**Comment by becks2000** [comment]
Hi,
I'm trying to do the same. Is it possible to run the default model without using the CUDA? Is the CPU version uploaded? Thanks

**Comment by bmccann** [comment]
Should be possible on https://github.com/salesforce/decaNLP/tree/pytorch_upgrade_041, which I'll merge ASAP. The migration somehow increased my GPU memory usage, so I'm holding off on merging until I figure out why that is. In the meantime, you can use that branch to run on CPU with new prebuilt Docker images. You will probably need to use a smaller --train_batch_tokens though.

**Comment by bmccann** [comment]
Should be updated now. Let me know (and reopen) if not!
