### ISSUE TITLE
What Chinese dataset  are available for training decaNLP?

### ISSUE THREAD

**Issue by threefoldo** [salesforce/decaNLP#29]
It's a little difficult to find Chinese dataset suitable for training decaNLP. Right now, all I have is: 1, douban movie review for sentiment analysis; 2, webqa from baidu. Is there any other data which can be used for training?

**Comment by bmccann** [comment]
Well, any data you can find should be easy enough to include, but I myself am not familiar with the landscape of Chinese datasets. We can keep this issue open for a while to see if anyone else watching might know of some good ones.

**Comment by dfenglei** [comment]
The follow is paper for DuReader: a Chinese Machine Reading Comprehension Dataset from Real-world Applications
https://arxiv.org/abs/1711.05073

**Comment by threefoldo** [comment]
Thanks. I had already studied this data. Among 90k questions, most answers are long sentences, not short phrases embedded in input sentences.
