### ISSUE TITLE
Missing Winograd schema url

### ISSUE THREAD

**Issue by quanvuong** [salesforce/decaNLP#34]
[Is there supposed to be a link to the schema.txt file here?](https://github.com/salesforce/decaNLP/blob/203a02e2326de65400a8d3dce63fdb0f4ae0c324/text/torchtext/datasets/generic.py#L777)

Thanks!

**Comment by quanvuong** [comment]
Is this the missing schema.txt file?

https://github.com/salesforce/decaNLP/blob/master/local_data/schema.txt

**Comment by dfenglei** [comment]
Yes.
You need do the following step.
---------------------------------------------
You will also need to make a .data directory and move the examples for the Winograd Schemas into it:

mkdir -p .data/schema
cp local_data/schema.txt .data/schema/
---------------------------------------------

**Comment by quanvuong** [comment]
Are there supposed to be less than 200 training samples for both training and validation? This seems low so I want to double-check this task is intended to be low-resource.

**Comment by bmccann** [comment]
Yes, this task is intended to be low resource
