### ISSUE TITLE
Error while validating models.

### ISSUE THREAD

**Issue by ashleyyy94** [salesforce/decaNLP#35]
Hi,

Whenever I try to validate my models or the pretrained models provided, I run into this error:

Example: nvidia-docker run -it --rm -v `pwd`:/decaNLP/  decanlp bash -c "python /decaNLP/predict.py --evaluate validation --path /decaNLP/mqan_decanlp_qa_first --checkpoint_name model.pth --gpu 0"

.
.
.
Loading from /decaNLP/mqan_decanlp_qa_first/model.pth
Initializing Model
Traceback (most recent call last):
  File "/decaNLP/predict.py", line 262, in <module>
    model = Model(field, args)
  File "/decaNLP/models/multitask_question_answering_network.py", line 32, in __init__
    if self.args.cove or self.args.intermediate_cove:
AttributeError: 'Namespace' object has no attribute 'intermediate_cove'

Is there a way to resolve this? Training the decaNLP Model runs win but validation throws this error.

Thank you!

**Comment by dfenglei** [comment]
yes, You can look the below for fixing this error.
https://github.com/salesforce/decaNLP/pull/33

**Comment by ashleyyy94** [comment]
Thank you. That helped to fix it!
