### ISSUE TITLE
Issue with running commands with the docker image provided

### ISSUE THREAD

**Issue by ashleyyy94** [salesforce/decaNLP#41]
Hi,

I'm trying to run validation on the pretrained model provided with this command: 
`nvidia-docker run -it --rm -v `pwd`:/decaNLP/  bmccann/decanlp:cuda9_torch041 -c "python /decaNLP/predict.py --evaluate validation --path /decaNLP/mqan_decanlp_qa_first_cpu --checkpoint_name iteration_1140000.pth --device 0"`

After the docker image is downloaded and installed, it gives this error:
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"-c\": executable file not found in $PATH": unknown.`

Trying to run the command above again produces this same error. May I know the solution for this?

Thank you!

**Comment by bmccann** [comment]
Thanks for pointing this out! I had somehow done a really bad find and replace when I changed the Docker image names and I left out the `bash` part. I've updated the README. The command I meant to give you was:

```bash
nvidia-docker run -it --rm -v `pwd`:/decaNLP/ -u $(id -u):$(id -g) bmccann/decanlp:cuda9_torch041 bash -c "python /decaNLP/predict.py --evaluate validation --path /decaNLP/mqan_decanlp_qa_first_cpu --checkpoint_name iteration_1140000.pth --device 0"
```
