### ISSUE TITLE
Evaluating custom dataset with dsEM metric

### ISSUE THREAD

**Issue by ashleyyy94** [salesforce/decaNLP#48]
Hi is there a way to evaluate datasets using the dsEM metric? Currently additional commands only support --bleu and --rouge.

Thank you.

**Comment by keskarnitish** [comment]
In conjunction with https://github.com/salesforce/decaNLP/issues/47, I believe you can add your task (as an argument flag or directly) into:

https://github.com/salesforce/decaNLP/blob/1e9605f246b9e05199b28bde2a2093bc49feeeaa/validate.py#L78

Closing for now, feel free to reopen.

**Comment by ashleyyy94** [comment]
Update: Adding a custom task as an argument flag does not work. I changed it to `"dialogue='woz' in task or 'custom' in task"`. However, since my dataset is in the {Context, Question, Answer} format, computeDialogue in [metrics.py](https://github.com/salesforce/decaNLP/blob/1e9605f246b9e05199b28bde2a2093bc49feeeaa/metrics.py#L348) will process the answer wrongly and give an incorrect answer, usually comprising of a single letter.
