### ISSUE TITLE
arguments.py CoAttentiveMultipointerGenerator doesn't exist

### ISSUE THREAD

**Issue by dougc333** [salesforce/decaNLP#5]
Maybe should be CoAttentivePointerGenerator for default? 

Line 57 in arguments.py is : default='CoattentiveMultipointerGenerator'
maybe should be default='CoattentivePointerGenerator'? 

else train.py fails.

**Comment by bmccann** [comment]
Ah yes, that should be fixed at ca1718b33ca346baccb76f186cb810b98a86245f
