### ISSUE TITLE
Bug with returning final state in PackedLSTM?

### ISSUE THREAD

**Issue by sidbrahma** [salesforce/decaNLP#9]
https://github.com/salesforce/decaNLP/blob/435cfcfcda3600d9bb86381ff4c20ef02e6e8960/models/common.py#L294

While returning final states in PackedLSTM, the line reads
`h, c = h[:, _indices, :], h[:, _indices, :]`
It should be
`h, c = h[:, _indices, :], c[:, _indices, :]`
right?

**Comment by bmccann** [comment]
Thanks! Should be fixed at 1c9f12b2984edc4b2ca5434e47d3e5fc932288d1
